import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsString, MinLength } from 'class-validator';

export class RegisterDeviceDto {
  @ApiProperty({ description: 'Reusable per-location setup code generated by the kiosk owner/admin' })
  @IsString()
  @MinLength(1)
  setupCode: string;

  @ApiPropertyOptional({ example: 'Computer 4' })
  @IsOptional()
  @IsString()
  label?: string;

  @ApiPropertyOptional({ description: 'Falls back to this if no label is given' })
  @IsOptional()
  @IsString()
  hostname?: string;

  @ApiPropertyOptional({
    description: 'Agent-generated local UUID (device.json) — stored for support/audit correlation only, not used for dedup logic',
  })
  @IsOptional()
  @IsString()
  deviceIdentifier?: string;

  @ApiPropertyOptional({ example: 'Windows 11 Pro 10.0.26200' })
  @IsOptional()
  @IsString()
  osVersion?: string;
}
