import { Transform } from 'class-transformer';
import {
  IsBoolean,
  IsDateString,
  IsEmail,
  IsInt,
  IsOptional,
  IsString,
  Length,
  Matches,
  Max,
  MaxLength,
  Min,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
export class CreateReviewerDto {
  @ApiProperty()
  @Transform(({ value }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @Length(1, 100)
  name: string;
  @ApiPropertyOptional()
  @IsOptional()
  @IsEmail()
  @MaxLength(254)
  email?: string;
  @ApiProperty() @IsDateString() expiresAt: string;
  @ApiProperty({ default: 1 })
  @IsInt()
  @Min(1)
  @Max(20)
  maxInstallations: number;
}
export class ReviewerAccessDto {
  @ApiProperty() @IsBoolean() enabled: boolean;
}
export class RedeemReviewerDto {
  @ApiProperty()
  @Transform(({ value }) =>
    typeof value === 'string'
      ? value.replace(/[-\s]/g, '').toUpperCase()
      : value,
  )
  @Matches(/^REV[0-9A-F]{24}$/)
  code: string;
  // Generated by the extension; allows safe retries of a lost redemption response.
  @ApiProperty() @Matches(/^[A-Za-z0-9_-]{43}$/) token: string;
}
